import { createHash, createHmac } from "node:crypto";

/**
 * P9 — minimal S3 SigV4 presigner for Cloudflare R2.
 *
 * Hand-rolled rather than pulling in @aws-sdk/client-s3 + the presigner: those
 * add ~15MB to a serverless bundle for one operation, and query-string SigV4
 * is a short, fully-specified algorithm. Everything here is the AWS spec —
 * "Authenticating Requests: Using Query Parameters (AWS Signature Version 4)".
 *
 * R2 is S3-compatible and always region `auto`. Nothing below is R2-specific,
 * so pointing S3_ENDPOINT at MinIO or S3 proper works unchanged.
 */

export interface StorageConfig {
  accountEndpoint: string;
  bucket: string;
  accessKeyId: string;
  secretAccessKey: string;
  region: string;
  /** Public base URL objects are served from (r2.dev, or a custom domain). */
  publicBaseUrl: string;
}

/**
 * Read config from the environment, or null when it isn't set up.
 *
 * Returning null rather than throwing is the phase's degradation rule: with no
 * keys the media library renders read-only and says so, instead of taking the
 * whole admin area down.
 */
export function getStorageConfig(): StorageConfig | null {
  const accountEndpoint = process.env.S3_ENDPOINT;
  const bucket = process.env.S3_BUCKET;
  const accessKeyId = process.env.S3_ACCESS_KEY_ID;
  const secretAccessKey = process.env.S3_SECRET_ACCESS_KEY;

  if (!accountEndpoint || !bucket || !accessKeyId || !secretAccessKey) return null;

  return {
    accountEndpoint: accountEndpoint.replace(/\/$/, ""),
    bucket,
    accessKeyId,
    secretAccessKey,
    region: process.env.S3_REGION ?? "auto",
    publicBaseUrl: (process.env.S3_PUBLIC_BASE_URL ?? `${accountEndpoint}/${bucket}`).replace(
      /\/$/,
      "",
    ),
  };
}

export function isStorageConfigured(): boolean {
  return getStorageConfig() !== null;
}

const ALGORITHM = "AWS4-HMAC-SHA256";

function sha256Hex(value: string): string {
  return createHash("sha256").update(value, "utf8").digest("hex");
}

function hmac(key: Buffer | string, value: string): Buffer {
  return createHmac("sha256", key).update(value, "utf8").digest();
}

/**
 * RFC 3986 encoding.
 *
 * `encodeURIComponent` leaves !'()* alone, and S3 rejects the signature if our
 * canonical request encodes a key even one character differently from the way
 * the service does. Object keys are generated by us and conservative, but a
 * filename-derived key would hit this immediately.
 */
function uriEncode(value: string, encodeSlash = true): string {
  return value
    .split("")
    .map((char) => {
      if (/[A-Za-z0-9\-._~]/.test(char)) return char;
      if (char === "/") return encodeSlash ? "%2F" : "/";
      return "%" + char.charCodeAt(0).toString(16).toUpperCase().padStart(2, "0");
    })
    .join("");
}

function signingKey(config: StorageConfig, dateStamp: string): Buffer {
  const kDate = hmac(`AWS4${config.secretAccessKey}`, dateStamp);
  const kRegion = hmac(kDate, config.region);
  const kService = hmac(kRegion, "s3");
  return hmac(kService, "aws4_request");
}

export interface PresignOptions {
  key: string;
  method?: "PUT" | "GET" | "DELETE";
  expiresIn?: number;
  contentType?: string;
}

/**
 * Presigned URL for a single object operation.
 *
 * The browser uploads straight to R2 with this — bytes never pass through a
 * Vercel function, which keeps uploads off the serverless body-size limit and
 * off the bandwidth bill entirely.
 */
export function presignUrl(config: StorageConfig, options: PresignOptions): string {
  const { key, method = "PUT", expiresIn = 600, contentType } = options;

  const now = new Date();
  const amzDate = now.toISOString().replace(/[:-]|\.\d{3}/g, "");
  const dateStamp = amzDate.slice(0, 8);

  const endpoint = new URL(config.accountEndpoint);
  const host = endpoint.host;
  // Path-style addressing (/{bucket}/{key}); R2 supports it, and it avoids
  // depending on how the endpoint was configured.
  const canonicalUri = `/${uriEncode(config.bucket, false)}/${uriEncode(key, false)}`;

  const credential = `${config.accessKeyId}/${dateStamp}/${config.region}/s3/aws4_request`;

  // Content-Type is signed when supplied, so the browser cannot upload a
  // different type than the one the server validated and recorded.
  const signedHeaderNames = contentType ? "content-type;host" : "host";
  const canonicalHeaders = contentType
    ? `content-type:${contentType}\nhost:${host}\n`
    : `host:${host}\n`;

  // Query parameters must be sorted by name for the canonical request.
  const query: [string, string][] = [
    ["X-Amz-Algorithm", ALGORITHM],
    ["X-Amz-Credential", credential],
    ["X-Amz-Date", amzDate],
    ["X-Amz-Expires", String(expiresIn)],
    ["X-Amz-SignedHeaders", signedHeaderNames],
  ];
  const canonicalQuery = query
    .map(([name, value]) => [uriEncode(name), uriEncode(value)] as [string, string])
    .sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0))
    .map(([name, value]) => `${name}=${value}`)
    .join("&");

  const canonicalRequest = [
    method,
    canonicalUri,
    canonicalQuery,
    canonicalHeaders,
    signedHeaderNames,
    // Presigned uploads stream the body, so its hash cannot be known here.
    "UNSIGNED-PAYLOAD",
  ].join("\n");

  const stringToSign = [
    ALGORITHM,
    amzDate,
    `${dateStamp}/${config.region}/s3/aws4_request`,
    sha256Hex(canonicalRequest),
  ].join("\n");

  const signature = createHmac("sha256", signingKey(config, dateStamp))
    .update(stringToSign, "utf8")
    .digest("hex");

  return `${endpoint.origin}${canonicalUri}?${canonicalQuery}&X-Amz-Signature=${signature}`;
}

/** Public URL an uploaded object is readable at. */
export function publicUrlFor(config: StorageConfig, key: string): string {
  return `${config.publicBaseUrl}/${uriEncode(key, false)}`;
}

/**
 * Object key for an upload.
 *
 * Content-addressed by checksum prefix rather than by filename: two admins
 * uploading "screenshot.png" must not collide, and a key that embeds the
 * user's filename verbatim is a path-traversal surface for no benefit. The
 * original name is kept in the database column instead, where it is data.
 */
export function buildObjectKey(folder: string, checksum: string, extension: string): string {
  const safeFolder = folder.replace(/[^a-z0-9-]/gi, "").toLowerCase() || "uploads";
  const safeExtension = extension.replace(/[^a-z0-9]/gi, "").toLowerCase() || "bin";
  return `${safeFolder}/${checksum.slice(0, 32)}.${safeExtension}`;
}

/** Server-side delete, used when an asset is removed from the library. */
export async function deleteObject(config: StorageConfig, key: string): Promise<boolean> {
  const url = presignUrl(config, { key, method: "DELETE", expiresIn: 60 });
  try {
    const response = await fetch(url, { method: "DELETE" });
    // S3 returns 204 for a successful delete and, by design, also for a key
    // that was already gone — both mean "not there any more".
    return response.ok || response.status === 404;
  } catch (error) {
    console.error("[storage] delete failed:", error);
    return false;
  }
}
